---

#
# Configure Mariadb
#

- name: generate mysqld_openstack.cnf (templates)
  template: src="mysqld_openstack.cnf.j2" dest=/etc/mysql/conf.d/mysqld_openstack.cnf
  notify: restart mariadb
  become: yes
  become_method: sudo

#- name: update mysql root password
#  mysql_user: name=root host={{ item }} password={{ MARIADB_ROOT_PASS }} priv=*.*:ALL,GRANT state=present
#  with_items:
#    - "127.0.0.1"
#    - localhost
#  become: yes
#  become_method: sudo
